version: '3.5'
services:
  backend:
    build:
      context: .
    command: bundle exec hanami server
    volumes:
      - ./:/quotes
    ports:
      - "2300:2300"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_admin_password
